In [1]:
import numpy as np
h_size = [100, 120,120,100,85,90,90,140,70,150]
h_rooms = [4,5,5,4,3,4,4,6,3,6]
h_price = [150000, 190000, 195000, 140000, 130000, 155000, 135000, 200000, 120000,225000]
array_s = np.array(h_size)
array_r = np.array(h_rooms)
array_p = np.array(h_price)
h_all = np.array ([array_s, array_r, array_p])
print (h_all,'\n')

[[   100    120    120    100     85     90     90    140     70    150]
 [     4      5      5      4      3      4      4      6      3      6]
 [150000 190000 195000 140000 130000 155000 135000 200000 120000 225000]] 



In [2]:
h_new = h_all.T
print (h_new, '\n')

[[   100      4 150000]
 [   120      5 190000]
 [   120      5 195000]
 [   100      4 140000]
 [    85      3 130000]
 [    90      4 155000]
 [    90      4 135000]
 [   140      6 200000]
 [    70      3 120000]
 [   150      6 225000]] 



In [3]:
print (h_new.shape)

(10, 3)


That is a 2D Array which has 10 Rows in Axis 1 and 3 Colummns in Axis 0

In [4]:
def matrix(row,col):
    #row = int(input('Enter row number:'))
    #col = int(input('Enter column number:'))
    list_all = []
    for i in range(1,row+1):

        if i%2 == 0:
            even_row = []
            for ii in range(1,col+1):
                if ii % 2 != 0:
                    even_row.append(1.)
                else:
                    even_row.append(0.)
            list_all.append(even_row)

        else:
            odd_row = []
            for iii in range(1,col+1):
                odd_row.append(1.)
            list_all.append(odd_row)
    ary_all = np.array(list_all)
    ary_new = ary_all.reshape(row,col)
    print('Shape (',row,'x',col,')')
    print(ary_new)

matrix(6,5)


Shape ( 6 x 5 )
[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
